schema_version = "1.0.0"

id = "zzamjak_3d_remesher"
version = "0.2.0"
name = "3D Remesher"
tagline = "특징선을 보존하는 실험 쿼드 메시 생성 도구"
maintainer = "zzamjak-cloud"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Mesh", "Modeling"]
